---
abstract: unknown
author:
  - 'Paul Miller <jettero@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.32, CPAN::Meta::Converter version 2.150010'
keywords:
  - imap
  - simple
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-IMAP-Simple
no_index:
  directory:
    - t
    - inc
requires:
  IO::Select: '0'
  IO::Socket: '0'
  Parse::RecDescent: '0'
  perl: '5.008'
resources:
  repository: http://github.com/jettero/net--imap--simple
version: '1.2211'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
